### ISSUE TITLE
Decouple Reports from this repo

### ISSUE THREAD

**Issue by vezzi** [SciLifeLab/NouGAT#21]

**Comment by remiolsen** [comment]
How about over time integrating it to ngi_reports. @ewels thoughts?

**Comment by ewels** [comment]
Absolutely, or at least some of the functionality. What code is there currently / what does it do?

**Comment by remiolsen** [comment]
Right now we have two reports. One that is very much [coupled](https://github.com/SciLifeLab/de_novo_scilife/blob/master/de_novo_scilife/QCcontrol.py) to the read QC part of the pipeline. Depending on which tools have been run, specified in a .yaml file generated at the start, it parses the output files (from Picard, Trimmomatic, fastqQC etc.) and dynamically builds a reportlab report from it.

The other report is generated after assembly using a somewhat standalone [script](https://github.com/SciLifeLab/de_novo_scilife/blob/master/sciLifeLab_utils/run_assembly_report.py). It copies the data for delivery, and for each assembler (also specified in a .yaml file) computes some stats and embed plots generated by assembly evaluation tools.

**Comment by ewels** [comment]
Ok, cool. I guess the simplest thing to do would be to get your code to generate a markdown file, and then use `ngi_reports` to convert that into PDF and HTML. I'm not familiar with reportlab, but this would mean that you get the consistent branding and everything that comes with `ngi_reports`.

If you want fuller integration, you could shift your code into a `ngi_reports` module, as we've done with the IGN Sample Report. That code scrapes the data from output files (including Picard) and plots graphs by calling functions in `ngi_visualizations`.

Up to you I guess!

**Comment by remiolsen** [comment]
#26 closes this issue. While it would be cool to move away from reportlab, it's not a high priority.
